### ISSUE TITLE
instructions for raising sequrity is incorrect

### ISSUE THREAD

**Issue by BitzComplete** [cormiertyshawn895/RecordingIndicatorUtility#4]
i tested this utility on macOS 12.4 (worked for me!) and decided to revert because of sequrity policy. i love the very clear instructions, however https://cormiertyshawn895.github.io/instruction/?arch=intel-raising has a crucial typo. See below:

>### Only allow sealed system snapshots 
>
>Type the following and press return:
> `csrutil authenticated-root` ~~disable~~ `enable`

<img src="https://user-images.githubusercontent.com/267391/178097396-de9bc5ab-0208-4e07-ae66-415eb84ab8b6.PNG" width=40% height=40%>

keep up the great work!

**Comment by Albino-Watermelon** [comment]
You are awesome. I thought I was gonna have to go through the trouble of downgrading my laptop using a backup because I was thinking 12.4 wasn't compatible. Thanks for pointing out that typo!

**Comment by joelle-snaith** [comment]
@Lagom-zz @Albino-Watermelon 

I’ve come here because I installed this on a new M1 MacBook and after restarting and toggling ON the per app settings button I was asked to restart again but then MacBook wouldn’t start up and has forced a complete reinstall of the OS 🥴. I have installed this twice before on 2 MacBooks running 12.3 in the past 6 months ( a stolen one and then a rental - am now on the replacement one ) and it worked a treat ( thank you 🙏🏼) I wonder if this time it caused the machine to force a resinstall because I typed disable instead of enable? Was rushing and didn’t check against the screenshots and assume the last two times I followed the screenshots not the text below. Good to hear it works on 12.4 - am tempted to try again as have a show on Saturday and really need this dot gone. Thanks for flagging the typo. 

Does anyone know though why the MacBook would have not started up and said I need to reinstall the OS? could it be the typo?

**Comment by joelle-snaith** [comment]
Ah I just realised this was to turn it all back on 😵‍💫 brain fried and stressed.  Now I’m really  unsure why my M1 made me reinstall the OS and wouldn’t boot up… it only happened after the first restart after changing the settings in terminal - and then toggling the button in the app itself which requires a restart to work

**Comment by joelle-snaith** [comment]
I've just deleted a a pretty frazzled comment where I said that installing this on 12.4 forced me to reinstall. I've reinstalled the OS, now on 12.5 and it appears to be working ok... not sure why the M1 didn't start up and ask for a reinstall - hopefully just fixed itself.

**Comment by cormiertyshawn895** [comment]
Good find! The typo is now [fixed](https://github.com/cormiertyshawn895/cormiertyshawn895.github.io/commit/4bae479b489e7eb296c4bc33f21b94d10457a094).

**Comment by FujiEple** [comment]
The instructions from the QR code still have the typo. 
I was forced to reinstall my OS from Recovery to regain access to my Mac.

**Comment by cormiertyshawn895** [comment]
If you re-install macOS, the app no longer takes effect on your Mac.
